version: "3.9"
services:
  builder-base:
    image: neso/env-builder-base-${TOOLCHAIN:-gcc-hipsycl}:${BUILDER_BASE_VERSION:-0.0.1}
    build:
      context: ..
      dockerfile: docker/builder-base/Dockerfile
      target: ${TOOLCHAIN:-gcc-hipsycl}
    pull_policy: never
  neso-env:
    image: neso/env-${TOOLCHAIN:-gcc-hipsycl}:${ENV_VERSION:-0.0.1}
    build:
      context: .
    container_name: neso-env
